import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter ({ subsets: ["latin"] });
/* const LINK = "http://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,0"; */

export const metadata = {
  title: "Weather App Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="http://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,0" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
